//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Examples
{
    using System;
    using System.Collections.Generic;
    
    public partial class FridayConfigs
    {
        public System.Guid Id { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime ExpiredTime { get; set; }
    }
}
