//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Examples
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public System.Guid Id { get; set; }
        public decimal Cost { get; set; }
        public int Count { get; set; }
        public string DisplayName { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> Order_Id { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
