//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Examples
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variants
    {
        public System.Guid Id { get; set; }
        public string Answer { get; set; }
        public int AnswersCount { get; set; }
        public System.Guid PollId { get; set; }
    
        public virtual Polls Polls { get; set; }
    }
}
