//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Examples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttestationPeriods
    {
        public AttestationPeriods()
        {
           // this.MonthPoints = new HashSet<MonthPoints>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int RequiredPoints { get; set; }
        public int StartPoints { get; set; }
        public string FromGrade { get; set; }
        public string Grade { get; set; }
        public System.Guid User_Id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<MonthPoints> MonthPoints { get; set; }
    }
}
