//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Examples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polls
    {
        public Polls()
        {
           // this.Variants = new HashSet<Variants>();
           // this.Users = new HashSet<Users>();
           // this.Users1 = new HashSet<Users>();
        }
    
        public System.Guid Id { get; set; }
        public int TypeId { get; set; }
        public int ForTypeId { get; set; }
        public string Question { get; set; }
        public System.DateTime PublishDate { get; set; }
        public bool isPublish { get; set; }
    
        public virtual ICollection<Variants> Variants { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Users> Users1 { get; set; }
    }
}
