//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Examples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
           // this.AttestationPeriods = new HashSet<AttestationPeriods>();
           // this.MonthPoints = new HashSet<MonthPoints>();
           // this.Orders = new HashSet<Orders>();
           // this.Polls = new HashSet<Polls>();
           // this.Polls1 = new HashSet<Polls>();
           // this.Roles = new HashSet<Roles>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> Group_Id { get; set; }
    
        public virtual ICollection<AttestationPeriods> AttestationPeriods { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual ICollection<MonthPoints> MonthPoints { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Polls> Polls { get; set; }
        public virtual ICollection<Polls> Polls1 { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
